# coding: utf-8
# ref: https://jekyllrb.com/docs/configuration/

title: 넷평 남짓한 공간
url: netpyoung.github.io/nf.example.shader/
description: netpyoung's shader example

author :
    name : Eunpyoung Kim
    email : netpyoung@gmail.com
    github : https://github.com/netpyoung


Paths :
    webpack: /webpack/dist

exclude: ["webpack/node_modules"]

incremental: true

defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"